Fixes python3 encoding compatibility problems
Write the log file with utf8 encoding.

0xab 0xbb doesn't exist in GBK.
Traceback (most recent call last):
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 930, in <module>
    sys.exit(main())
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 920, in main
    code = test_suite.run(options.command, args,
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 842, in run
    progress.has_run(result)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 669, in has_run
    result.report_outcome(True)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 439, in report_outcome
    self.write_output(sys.stdout)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 453, in write_output
    target.write("--- errors ---  \n %s" % error)
UnicodeEncodeError: 'gbk' codec can't encode character '\xab' in position 52: illegal multibyte sequence

"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/runner/work/jerryscript/jerryscript/tools/runners/test262-harness.py", line 658, in test_case_run_process
    return case.run()
  File "/home/runner/work/jerryscript/jerryscript/tools/runners/test262-harness.py", line 623, in run
    result = self.run_test_in(tmp)
  File "/home/runner/work/jerryscript/jerryscript/tools/runners/test262-harness.py", line 617, in run_test_in
    (code, out, err) = TestCase.execute(command)
  File "/home/runner/work/jerryscript/jerryscript/tools/runners/test262-harness.py", line 605, in execute
    err = stderr.read()
  File "/home/runner/work/jerryscript/jerryscript/tools/runners/test262-harness.py", line 405, in read
    return result.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 255: invalid continuation byte
"""

Traceback (most recent call last):
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 933, in <module>
    sys.exit(main())
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 921, in main
    code = test_suite.run(options.command, args,
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 821, in run
    cases = self.enumerate_tests(tests, command_template)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 768, in enumerate_tests
    strict_case = TestCase(self, name, full_path, True, command_template)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 486, in __init__
    self.contents = file_desc.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 438: illegal multibyte sequence
=== Summary - updating excludelist ===

"""
Traceback (most recent call last):
  File "C:\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 658, in test_case_run_process
    return case.run()
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 623, in run
    result = self.run_test_in(tmp)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 612, in run_test_in
    tmp.write(self.get_source())
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 564, in get_source
    self.get_additional_includes() + \
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 548, in get_additional_includes
    return '\n'.join([self.suite.get_include(include) for include in self.get_include_list()])
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 548, in <listcomp>
    return '\n'.join([self.suite.get_include(include) for include in self.get_include_list()])
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 738, in get_include
    contents = file_desc.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 33422: illegal multibyte sequence
"""

If the temp file are opened in text mode, when concat the js test
file, it's will alter the js content, especially about the raw literal string.
It's will alter the raw literal string result on Windows.
This is a partial fixes es2015 tests:
```
  built-ins/String/raw/special-characters.js
  language/expressions/template-literal/tv-line-continuation.js
  language/expressions/template-literal/tv-line-terminator-sequence.js
```
in https://github.com/jerryscript-project/jerryscript/issues/4384

JerryScript-DCO-1.0-Signed-off-by: Yonggang Luo luoyonggang@gmail.com