0xab 0xbb doesn't exist in GBK.
Traceback (most recent call last):
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 930, in <module>
    sys.exit(main())
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 920, in main
    code = test_suite.run(options.command, args,
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 842, in run
    progress.has_run(result)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 669, in has_run
    result.report_outcome(True)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 439, in report_outcome
    self.write_output(sys.stdout)
  File "C:\work\study\languages\typescript\jerryscript\tools\runners\test262-harness.py", line 453, in write_output
    target.write("--- errors ---  \n %s" % error)
UnicodeEncodeError: 'gbk' codec can't encode character '\xab' in position 52: illegal multibyte sequence